export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_RUN_BEGIN = "CREATE_RUN_BEGIN";
export const CREATE_RUN_SUCCESS = "CREATE_RUN_SUCCESS";
export const CREATE_RUN_ERROR = "CREATE_RUN_ERROR";

export const GET_RUNS_BEGIN = "GET_RUNS_BEGIN";
export const GET_RUNS_SUCCESS = "GET_RUNS_SUCCESS";

export const SET_EDIT_RUN = "SET_EDIT_RUN";

export const DELETE_RUN_BEGIN = "DELETE_RUN_BEGIN";

export const EDIT_RUN_BEGIN = "EDIT_RUN_BEGIN";
export const EDIT_RUN_SUCCESS = "EDIT_RUN_SUCCESS";
export const EDIT_RUN_ERROR = "EDIT_RUN_ERROR";

export const SHOW_STATS_BEGIN = "SHOW_STATS_BEGIN";
export const SHOW_STATS_SUCCESS = "SHOW_STATS_SUCCESS";
